### ISSUE TITLE
Compilation on draco with petsc-real/3.10

### ISSUE THREAD

**Issue by amicitas** [landreman/sfincs#4]
Compilation on draco or cobra is apparently currently broken.  This appears to be an issue with the new version of petsc-real.

I have tried this with:

- petsc-real/3.10
- petsc-real-openmp/3.10

(readHDF5Input.F90(11): #error: can't find include file: petsc/finclude/petscsysdef.h)

The error message is during compilation of mini_libstell:
`readHDF5Input.F90(11): #error: can't find include file: petsc/finclude/petscsysdef.h`

Here is the complete message:
`mpiifort -I/mpcdf/soft/SLE_12_SP3/packages/haswell/hdf5/intel_18_0_3-impi_2018_3/1.8.20/include -I/mpcdf/soft/SLE_12_SP3/packages/haswell/petsc-real-openmp/intel_18_0_3-impi_2018_3/3.10.3/include -I/mpcdf/soft/SLE_12_SP3/packages/haswell/petsc-real-openmp/intel_18_0_3-impi_2018_3/3.10.3//include -I/mpcdf/soft/SLE_12_SP3/packages/haswell/netcdf-mpi/intel_18_0_3-impi_2018_3/4.4.1/include -DUSE_NETCDF -I mini_libstell -c readHDF5Input.F90
readHDF5Input.F90(11): #error: can't find include file: petsc/finclude/petscsysdef.h
makefile:56: recipe for target 'readHDF5Input.o' failed
make: *** [readHDF5Input.o] Error 1`

**Comment by amollen** [comment]
There are issues with building SFINCS on the IPP clusters, and I haven't managed to get SFINCS to work for petsc > 3.7.6 on them. On Cobra I have managed to build SFINCS with my own local install of Petsc-3.7.6 but the performance is very poor when running the code.

I would recommend using Draco with the following commands at login:

module purge
module load intel/17.0
module load mkl/2017.4 
module load impi/2017.4
module load hdf5-serial
module load netcdf-serial
module load anaconda/2/5.1

setenv PETSC_ARCH 20170728-10-removingMPI_shouldWork
setenv PETSC_DIR /draco/u/mlan/petsc-3.7.6
setenv PETSC_HOME /draco/u/mlan/petsc-3.7.6
setenv PATH ${PATH}:${HDF5_HOME}/bin
setenv SFINCS_SYSTEM draco
setenv LD_LIBRARY_PATH ${HDF5_HOME}/lib:${NETCDF_HOME}/lib

**Comment by landreman** [comment]
The version of master I committed just now compiles, links, and runs on Draco with
module load hdf5-serial netcdf-serial petsc-real-openmp
All the 'make test' tests pass.

**Comment by landreman** [comment]
Sfincs now also compiles/links/runs on Cobra with those same modules (hdf5-serial netcdf-serial petsc-real-openmp) and all the 'make test' tests pass on Cobra.

**Comment by amicitas** [comment]
Compilation works for me on draco for revision 0f58884 (when the patch was made), but is broken again for the most current revision, 3899756.  

The new error is:

`solver.F90:(.text+0x6dc): undefined reference to `pcfactorsetmatsolverpackage_'`

**Comment by landreman** [comment]
I think the problem was that the changes to solver.F90 in c479bf3 un-did some changes in 72b895e to handle recent PETSc versions. The version of master I committed just now compiles, links, and runs on Draco with
module load hdf5-serial netcdf-serial petsc-real-openmp
All the 'make test' tests pass on Draco now. I'm getting some errors related to hdf5 however on Cori and my macbook - I'll continue to work on these problems.

**Comment by lazersos** [comment]
Matt, in `updateBoozerGeometry.F90` I found I had to redefine the header `../PETScVersions.F90` to `PETScVersions.F90` to get the code to compile on Draco.

**Comment by landreman** [comment]
That `#include` line in `updateBoozerGeometry.F90` is now fixed in master.
